"""
Streamlit Frontend — AI-Powered RAG System
==========================================
Interactive web interface for the hybrid retrieval system.
Connects to the FastAPI backend via HTTP.
"""

import time
import requests
import streamlit as st

API_BASE = "http://localhost:8000"

# ─── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="AI-Powered RAG System",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─── Custom CSS ───────────────────────────────────────────────────────────────
st.markdown("""
<style>
    .metric-card {
        background: #1e1e2e;
        border: 1px solid #313244;
        border-radius: 8px;
        padding: 16px;
        text-align: center;
    }
    .result-card {
        background: #1e1e2e;
        border-left: 3px solid #89b4fa;
        padding: 12px 16px;
        margin-bottom: 8px;
        border-radius: 4px;
    }
    .score-badge {
        background: #313244;
        color: #89b4fa;
        padding: 2px 8px;
        border-radius: 12px;
        font-size: 0.8em;
        font-family: monospace;
    }
</style>
""", unsafe_allow_html=True)


# ─── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("🔍 RAG System")
    st.caption("Hybrid BM25 + E5 Retrieval")
    st.divider()

    method = st.radio("Retrieval Method", ["hybrid", "sparse", "dense"], index=0)

    alpha = st.slider(
        "Fusion Parameter α",
        min_value=0.0, max_value=1.0, value=0.70, step=0.05,
        help="α=0.70 is empirically optimal on MS MARCO (p<0.001). Higher = more dense (semantic); lower = more sparse (lexical).",
        disabled=(method != "hybrid"),
    )

    k = st.slider("Number of Results", min_value=1, max_value=20, value=5)
    generate = st.checkbox("Generate Answer (GPT-4)", value=False)

    st.divider()
    st.markdown("**Key Metrics (α=0.70)**")
    st.metric("Recall@10", "93.0%", "+11.4% vs E5 only")
    st.metric("MRR", "1.0", "Perfect ranking")
    st.metric("Latency", "710ms", "-99.2% vs baseline")
    st.metric("Storage", "4.46 MB", "-99.8% vs naive")


# ─── Main area ────────────────────────────────────────────────────────────────
st.title("AI-Powered Q&A System")
st.caption("Hybrid RAG: BM25 + E5 Embeddings · MSc Thesis · Rohith Kumar Reddipogula")

query = st.text_input(
    "Enter your question",
    placeholder="e.g. What is machine learning? How does FAISS work?",
    label_visibility="collapsed",
)

col_search, col_health = st.columns([1, 4])
with col_search:
    search_clicked = st.button("🔍 Search", type="primary", use_container_width=True)
with col_health:
    health_clicked = st.button("📊 System Health", use_container_width=True)

# ─── System health ────────────────────────────────────────────────────────────
if health_clicked:
    try:
        resp = requests.get(f"{API_BASE}/health", timeout=5)
        h = resp.json()
        st.subheader("System Health")
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("Status", h["status"].upper())
        c2.metric("Uptime", f"{h['uptime_seconds']:.0f}s")
        c3.metric("Passages", f"{h['passages_loaded']:,}")
        c4.metric("Avg Latency", f"{h['retriever_stats'].get('avg_latency_ms', 0):.0f}ms")

        st.json(h["cache_stats"])
    except Exception as e:
        st.error(f"Could not reach backend: {e}")

# ─── Search ────────────────────────────────────────────────────────────────────
if search_clicked and query.strip():
    payload = {
        "query": query.strip(),
        "method": method,
        "alpha": float(alpha),
        "k": k,
        "generate_answer": generate,
    }

    with st.spinner("Retrieving..."):
        t0 = time.time()
        try:
            resp = requests.post(f"{API_BASE}/search", json=payload, timeout=30)
            resp.raise_for_status()
            data = resp.json()
        except requests.exceptions.ConnectionError:
            st.error("❌ Cannot connect to backend at localhost:8000. Is it running?")
            st.stop()
        except Exception as e:
            st.error(f"Search failed: {e}")
            st.stop()

    # ─── Metrics row
    st.divider()
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Results", len(data["results"]))
    m2.metric("Latency", f"{data['latency_ms']:.0f}ms")
    m3.metric("Method", data["method"].title())
    m4.metric("α", f"{data['alpha']:.2f}" if data["method"] == "hybrid" else "N/A")

    # ─── LLM Answer
    if generate and data.get("answer"):
        st.subheader("💡 Generated Answer")
        st.info(data["answer"])
        st.caption("Answer generated by GPT-4 using retrieved passages as context only.")

    # ─── Results
    st.subheader(f"📄 Retrieved Passages ({len(data['results'])} results)")
    for r in data["results"]:
        with st.expander(f"Rank {r['rank']} · Score {r['score']:.4f} · Doc {r['doc_id']}", expanded=(r["rank"] == 1)):
            st.write(r["text"])
            c1, c2, c3 = st.columns(3)
            c1.markdown(f"<span class='score-badge'>Hybrid: {r['score']:.4f}</span>", unsafe_allow_html=True)
            c2.markdown(f"<span class='score-badge'>BM25: {r['bm25_score']:.4f}</span>", unsafe_allow_html=True)
            c3.markdown(f"<span class='score-badge'>E5: {r['dense_score']:.4f}</span>", unsafe_allow_html=True)

elif search_clicked and not query.strip():
    st.warning("Please enter a query.")

# ─── Footer ───────────────────────────────────────────────────────────────────
st.divider()
st.caption(
    "Built by Rohith Kumar Reddipogula · MSc Data Science, University of Europe for Applied Sciences, Potsdam · "
    "[GitHub](https://github.com/rohithkumarreddipogula) · "
    "[Live Demo](https://sage-bunny-d1e261.netlify.app)"
)
